name: Format PR

on:
  issue_comment:
    types: [created]

jobs:
  format-code:
    name: Auto-format Code
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/format') &&
      (github.event.comment.author_association == 'OWNER' ||
       github.event.comment.author_association == 'MEMBER' ||
       github.event.comment.author_association == 'COLLABORATOR')

    steps:
      - name: Get PR branch
        uses: actions/github-script@v7
        id: get-pr
        with:
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            return {
              head_ref: pullRequest.head.ref,
              head_sha: pullRequest.head.sha,
              base_ref: pullRequest.base.ref
            };

      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ fromJson(steps.get-pr.outputs.result).head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Format code
        run: |
          echo "🎨 Auto-formatting code..."
          npm run format:fix
          npm run lint:fix

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          if git diff --exit-code; then
            echo "No formatting changes needed"
          else
            git add .
            git commit -m "style: auto-format code

            🤖 Generated with [GitHub Actions](https://github.com/actions)
            
            Co-Authored-By: GitHub Action <action@github.com>"
            git push
            
            echo "✅ Code has been formatted and committed"
          fi

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Code has been automatically formatted and linted!'
            })